language: python

python:
    - "3.7"

services:
    - postgresql

install:
    - pipenv install  --skip-lock
script:
    - coverage run --source='instagram/apps' manage.py test && coverage report

after_success:
    - coveralls